# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file
#  '.\secao_7\379 qtdesigner\ui\window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 467)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelResult = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setStrikeOut(False)
        self.labelResult.setFont(font)
        # self.labelResult.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignCenter)
        self.labelResult.setAlignment(QtCore.Qt.AlignCenter)  # type: ignore
        self.labelResult.setObjectName("labelResult")
        self.gridLayout.addWidget(self.labelResult, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.gridLayout_2.addWidget(self.labelName, 0, 0, 1, 1)
        self.lineName = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lineName.setFont(font)
        self.lineName.setObjectName("lineName")
        self.gridLayout_2.addWidget(self.lineName, 0, 1, 1, 1)
        self.buttonSend = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.buttonSend.setFont(font)
        self.buttonSend.setObjectName("buttonSend")
        self.gridLayout_2.addWidget(self.buttonSend, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 603, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelResult.setText(_translate("MainWindow", "Não tem nada aqui"))
        self.labelName.setText(_translate("MainWindow", "Seu nome:"))
        self.lineName.setPlaceholderText(_translate("MainWindow",
                                                    "Digite seu nome"))
        self.buttonSend.setText(_translate("MainWindow", "Enviar"))
